### ISSUE TITLE
typescript@4.2.4 build fails with error TS2344

### ISSUE THREAD

**Issue by georgescubogdan** [angular-cms/angular-cms#157]
src/modules/content/content-version.service.ts:6:91 - error TS2344: Type 'V' does not satisfy the constraint 'IBaseDocument'.
  Type 'IContentVersionDocument' is not assignable to type 'IBaseDocument'.
    The types of 'delete(...).$where(...).count(...).distinct(...).replaceOne' are incompatible between these types.
      Type '(filter?: FilterQuery<V>, replacement?: _AllowStringsForIds<LeanDocument<V>>, options?: QueryOptions, callback?: (err: any, res: any) => void) => Query<...>' is not assignable to type '(filter?: FilterQuery<IBaseDocument>, replacement?: _AllowStringsForIds<LeanDocument<IBaseDocument>>, options?: QueryOptions, callback?: (err: any, res: any) => void) => Query<...>'.
        Types of parameters 'replacement' and 'replacement' are incompatible.
          Type '_AllowStringsForIds<LeanDocument<IBaseDocument>>' is not assignable to type '_AllowStringsForIds<LeanDocument<V>>'.

6 export class ContentVersionService<V extends IContentVersionDocument> 
extends BaseService<V> {
  
                    ~

src/modules/content/content.model.ts:77:93 - error TS2344: Type 'T' does not satisfy the constraint 'IBaseDocument'.
  Type 'IContentVersionDocument' is not assignable to type 'IBaseDocument'.
    The types of 'delete(...).$where(...).count(...).distinct(...).replaceOne' are incompatible between these types.
      Type '(filter?: FilterQuery<T>, replacement?: _AllowStringsForIds<LeanDocument<T>>, options?: QueryOptions, callback?: (err: any, res: any) => void) => Query<...>' is not assignable to type '(filter?: FilterQuery<IBaseDocument>, replacement?: _AllowStringsForIds<LeanDocument<IBaseDid) => Query<...>'.
        Types of parameters 'replacement' and 'replacement' are incompatible.
          Type '_AllowStringsForIds<LeanDocument<IBaseDocument>>' is not assignable to type '_AllowStringsForIds<LeanDocument<T>>'.

77 export interface IContentVersionModel<T extends IContentVersionDocument> extends IBaseModel<T> { }

**Comment by danghung1202** [comment]
@georgescubogdan , yes, for now, It only support build for typescript@4.1.5. It seems there are some syntaxs not work for higher version. Need to investigate more to make it work with typescript@4.2.4. Could you help and create a PR?

**Comment by georgescubogdan** [comment]
I am looking into it. For now all I can say is that the latest typescript version doesn't support the multiple type constraint workaround (super-interface) for generic types and I think it's more a ts bug than a syntax error.

**Comment by danghung1202** [comment]
@georgescubogdan , sound good. Thank you for clarify. Btw, I am going to relocate this project to new Org with new brand and new logo. This cms has named TypiJS and located under Org [https://github.com/typijs](https://github.com/typijs) and it will released the beta version soon.

I am going to document step by step so you can easy understand the structure code, idea, architecture ...

Hope you can continue support and be a part of project
